### ISSUE TITLE
Missing evidence in UT when export is failing

### ISSUE THREAD

**Issue by Japoivvb** [Getsu05/M06UF1P1#9]
https://github.com/Getsu05/M06UF1P1/blob/08e273040563457e4f47a7e2570cd9463e76f68b/dam1_m03_uf6_jdbc_shop_solved/src/dao/DaoImplXml.java#L60

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

The issue is that the inventory is being sorted by stock in descending order before writing it to the XML file. This sorting should be removed to maintain the original order of the products. We'll remove the sorting line from the writeInventory method in DaoImplXml.java.

You can review changes in this commit: https://github.com/lattaai12/Getsu05-M06UF1P1-9/commit/dfd8ea496c3affa0d2293450d7122cab12a8c6be.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
